const char* html_template = 
    "<!DOCTYPE html><html><head><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">"
    "<title>CRSF Bridge Config</title>"
    "<style>"
    "body { font-family: Arial, sans-serif; background-color: #121212; color: #ffffff; margin: 0; padding: 20px; display: flex; justify-content: center; align-items: center; min-height: 100vh; }"
    ".container { background-color: #1e1e1e; padding: 30px; border-radius: 10px; box-shadow: 0 4px 8px rgba(0,0,0,0.5); width: 100%; max-width: 400px; }"
    "h2 { text-align: center; margin-top: 0; color: #4CAF50; }"
    "h3 { border-bottom: 1px solid #333; padding-bottom: 5px; color: #aaa; font-size: 16px; margin-top: 25px;}"
    "label { font-size: 14px; color: #bbb; display: block; margin-top: 10px; }"
    "input[type=text], input[type=number] { width: 100%; padding: 10px; margin-top: 5px; border: 1px solid #333; border-radius: 4px; box-sizing: border-box; background-color: #2a2a2a; color: #fff; font-size: 16px; }"
    "input[type=checkbox] { transform: scale(1.5); margin-right: 10px; }"
    ".checkbox-container { display: flex; align-items: center; margin-top: 15px; margin-bottom: 10px; }"
    "input[type=submit] { width: 100%; background-color: #4CAF50; color: white; padding: 14px; margin-top: 25px; border: none; border-radius: 4px; cursor: pointer; font-size: 16px; font-weight: bold; }"
    "input[type=submit]:hover { background-color: #45a049; }"
    "</style>"
    "<script>"
    "function toggleStatic() {"
    "    var isChecked = document.getElementById('use_static').checked;"
    "    document.getElementById('static_settings').style.display = isChecked ? 'block' : 'none';"
    "}"
    "window.onload = toggleStatic;"
    "</script>"
    "</head><body>"
    "<div class=\"container\"><h2>CRSF UDP Bridge</h2>"
    "<form action=\"/config\" method=\"POST\">"
    
    "<h3>Target Destination (UDP)</h3>"
    "<label>Target IP Address</label>"
    "<input type=\"text\" name=\"ip\" value=\"%s\" required>"
    "<label>Target UDP Port</label>"
    "<input type=\"number\" name=\"port\" value=\"%d\" required>"
    
    "<h3>Local ESP32 Network</h3>"
    "<div class=\"checkbox-container\">"
    "<input type=\"checkbox\" id=\"use_static\" name=\"use_static\" value=\"1\" %s onchange=\"toggleStatic()\">"
    "<label style=\"margin-top:0;\">Use Static IP</label>"
    "</div>"
    
    "<div id=\"static_settings\">"
    "<label>Local IP Address</label>"
    "<input type=\"text\" name=\"local_ip\" value=\"%s\">"
    "<label>Subnet Mask</label>"
    "<input type=\"text\" name=\"local_mask\" value=\"%s\">"
    "<label>Gateway</label>"
    "<input type=\"text\" name=\"local_gw\" value=\"%s\">"
    "</div>"
    
    "<input type=\"submit\" value=\"Save & Reboot\">"
    "</form></div></body></html>";