const char* html_template = 
    "<!DOCTYPE html><html><head><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">"
    "<title>CRSF Bridge Config</title>"
    "<style>"
    "body { font-family: Arial, sans-serif; background-color: #121212; color: #ffffff; margin: 0; padding: 20px; display: flex; justify-content: center; align-items: center; height: 100vh; }"
    ".container { background-color: #1e1e1e; padding: 30px; border-radius: 10px; box-shadow: 0 4px 8px rgba(0,0,0,0.5); width: 100%; max-width: 400px; }"
    "h2 { text-align: center; margin-top: 0; color: #4CAF50; }"
    "label { font-size: 14px; color: #bbb; }"
    "input[type=text], input[type=number] { width: 100%; padding: 12px 20px; margin: 8px 0 20px; display: inline-block; border: 1px solid #333; border-radius: 4px; box-sizing: border-box; background-color: #2a2a2a; color: #fff; font-size: 16px; }"
    "input[type=submit] { width: 100%; background-color: #4CAF50; color: white; padding: 14px 20px; margin: 8px 0; border: none; border-radius: 4px; cursor: pointer; font-size: 16px; font-weight: bold; }"
    "input[type=submit]:hover { background-color: #45a049; }"
    "</style></head><body>"
    "<div class=\"container\"><h2>CRSF UDP Bridge</h2>"
    "<form action=\"/config\" method=\"POST\">"
    "<label>Target IP Address</label>"
    "<input type=\"text\" name=\"ip\" value=\"%s\" maxlength=\"15\" required>"
    "<label>Target UDP Port</label>"
    "<input type=\"number\" name=\"port\" value=\"%d\" min=\"1\" max=\"65535\" required>"
    "<input type=\"submit\" value=\"Save Configuration\">"
    "</form></div></body></html>";